#!/usr/bin/env python


import subprocess
import json
import paramiko


def _do(ssh, command):
    stdin, stdout, stderr = ssh.exec_command(command)
    print stdout.read()


with open("data.json") as f:
    data = json.loads(f.read())

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

masterIp = data["Controller"]

for (name, ip) in data.items():
    print name, " ", ip
    ssh.connect(ip, username="root")
    _do(ssh, 'service salt-minion stop')
    _do(ssh, 'wget -O - https://repo.saltstack.com/apt/debian/8/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -')
    _do(ssh, 'echo "deb http://repo.saltstack.com/apt/debian/8/amd64/latest jessie main" >> /etc/apt/sources.list')
    _do(ssh, 'apt-get update')
    _do(ssh, 'apt-get install salt-minion --yes')
    stdin, stdout, stderr = ssh.exec_command('echo "minion_%s" > /etc/salt/minion_id' % name)
    # for everbody
    stdin, stdout, stderr = ssh.exec_command("echo %s salt >> /etc/hosts" % masterIp)
    print stdout.read()
    _do(ssh, 'echo "roles:" > /etc/salt/grains')
    _do(ssh, 'mkdir -p /srv/pillar/')
    _do(ssh, 'echo "mine_functions:" > /srv/pillar/swift.sls')
    _do(ssh, 'echo "  network.ip_addrs: [eth0]"  >> /srv/pillar/swift.sls')
    _do(ssh,'echo "base:" > /srv/pillar/top.sls')
    _do(ssh,'echo "  \'*\':" >> /srv/pillar/top.sls')
    _do(ssh,'echo "    - swift" >> /srv/pillar/top.sls')
    if (name == "Controller"):
        stdin, stdout, stderr = ssh.exec_command('apt-get install salt-master --yes')
        print stdout.read()
        stdin, stdout, stderr = ssh.exec_command('echo "fileserver_backend:" >> /etc/salt/master')
        print stdout.read()
        stdin, stdout, stderr = ssh.exec_command('echo "  - roots" >> /etc/salt/master')
        print stdout.read()
        stdin, stdout, stderr = ssh.exec_command('echo "  - minion" >> /etc/salt/master')
        print stdout.read()
        stdin, stdout, stderr = ssh.exec_command('echo "  - git" >> /etc/salt/master')
        print stdout.read()
        stdin, stdout, stderr = ssh.exec_command('echo "" >> /etc/salt/master')
        print stdout.read()
        stdin, stdout, stderr = ssh.exec_command('echo "file_recv: True" >> /etc/salt/master')
        print stdout.read()
        stdin, stdout, stderr = ssh.exec_command('echo "auto_accept: True" >> /etc/salt/master')
        print stdout.read()
        stdin, stdout, stderr = ssh.exec_command('echo "open_mode: True" >> /etc/salt/master')
        print stdout.read()
        stdin, stdout, stderr = ssh.exec_command('service salt-master restart')
        print stdout.read()
        print "Finish"
    elif (name == "VHG"):
        _do(ssh, 'echo "  - core" >> /etc/salt/grains')
        _do(ssh, 'echo "  - vhg" >> /etc/salt/grains')
    elif (name == "CDN-LB"):
        _do(ssh, 'echo "  - swift_proxy" >> /etc/salt/grains')
        _do(ssh, 'echo "  - core" >> /etc/salt/grains')
        _do(ssh, 'echo "  - worker" >> /etc/salt/grains')
        _do(ssh, 'echo "  - broker" >> /etc/salt/grains')
        _do(ssh, 'echo "  - frontend" >> /etc/salt/grains')
    elif (name == "CDN-1"):
        _do(ssh, 'echo "  - core" >> /etc/salt/grains')
        _do(ssh, 'echo "  - worker" >> /etc/salt/grains')
        _do(ssh, 'echo "  - swift_object" >> /etc/salt/grains')
    elif (name == "CDN-2"):
        _do(ssh, 'echo "  - core" >> /etc/salt/grains')
        _do(ssh, 'echo "  - woker" >> /etc/salt/grains')
        _do(ssh, 'echo "  - swift_object" >> /etc/salt/grains')
    stdin, stdout, stderr = ssh.exec_command("service salt-minion restart")
    print stdout.read()
