#!/usr/bin/env python


import subprocess
import json
import paramiko


def _do(ssh, command):
    stdin, stdout, stderr = ssh.exec_command(command)
    print stdout.read()




with open("data.json") as f:
    data = json.loads(f.read())

data2 = {};
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
for (name, ip) in data.items():
    name2 = name.split(".");
    try:
        data2[name2[0]][name2[1]] = ip;
    except:
        data2[name2[0]] = {};
        data2[name2[0]][name2[1]] = ip;

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

masterIp = data2["Controller"]["management"]
for (name, ips) in data2.items():
    print name, " ", ips, " connect to ", ips["management"]
    ssh.connect(ips["management"], username="root")
    _do(ssh, 'rm /srv/pillar/ips.sls')
    _do(ssh, 'rm /etc/salt/grains')
    _do(ssh, 'apt-get remove salt-minion --yes')
    _do(ssh, 'rm /etc/salt/minion_id')
    _do(ssh, "sed '/salt/d' /etc/hosts")
    _do(ssh, "sed '/saltstack/d' /etc/apt/sources.list")
    if (name == "Controller"):
        stdin, stdout, stderr = ssh.exec_command('apt-get remove salt-master --yes')
        print stdout.read()
        stdin, stdout, stderr = ssh.exec_command('rm  /etc/salt/master')
        print stdout.read()
        print "Finish"

print "Finish complete"
