# -*- mode: ruby -*-
# vi: set ft=ruby :


boxes = [

	{
        :name => "CDN-LB",
        :eth1 => "10.1.2.2",
        :eth2 => "10.1.3.2",
        :eth3 => "10.1.4.2",
        :eth4 => "10.1.1.2",
        :mem => "1024",
        :cpu => "1",
        :nodetype => "swift_proxy"
    },
    {
        :name => "CDN-1",
        :eth1 => "10.1.2.4",
        :eth2 => "10.1.3.4",
        :eth3 => "10.1.4.4",
        :mem => "1024",
        :cpu => "1",
        :nodetype => "swift_object"
    },
    {
        :name => "CDN-2",
        :eth1 => "10.1.2.5",
        :eth2 => "10.1.3.5",
        :eth3 => "10.1.4.5",
        :eth4 => "10.1.1.5",
        :mem => "1024",
        :cpu => "1",
        :nodetype => "swift_object"
    },   
	{
        :name => "VHG",
        :eth1 => "10.1.2.3",
        :eth2 => "10.1.3.3",
        :mem => "512",
        :cpu => "1",
        :nodetype => "vhg"
    },    
    {
        :name => "Controller",
        :eth1 => "10.1.2.254",
        :eth2 => "10.1.3.254",
        :eth3 => "10.1.4.254",
        :mem => "512",
        :cpu => "1",
        :nodetype => "Controller"
    }
]


$controleur = <<CONTROLLER

echo '{"Controller.management":"10.1.2.254","Controller.data_in":"10.1.4.254","VHG.management":"10.1.2.3","VHG.Floating_IP":"10.1.1.3","VHG.data_in":"10.1.4.3","CDN-LB.management":"10.1.2.2","CDN-LB.Floating_IP":"10.1.1.2","CDN-LB.storage":"10.1.3.2","CDN-LB.data_in":"10.1.4.2","CDN-1.management":"10.1.2.4","CDN-1.storage":"10.1.3.4","CDN-1.data_in":"10.1.4.4","CDN-2.management":"10.1.2.5","CDN-2.storage":"10.1.3.5","CDN-2.data_in":"10.1.4.5"}'>/root/data.json
wget https://raw.githubusercontent.com/dngroup/t-nova/master/controller/vanilla /root/vanilla
chmod 777 /root/vanilla
cd /root
./vanilla

CONTROLLER


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  
  config.vm.box = "../package.box"
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
  config.ssh.username = "root"
  config.ssh.password = "toor"
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]


      config.vm.network :private_network, ip: opts[:eth1]
      config.vm.network :private_network, ip: opts[:eth2]

      config.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] = opts[:mem]
        v.vmx["numvcpus"] = opts[:cpu]
      end

      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      end

      if opts[:nodetype] == "Controller"
          config.vm.provision :shell, inline: $controleur
      end
      
      
    end
  end
end
